AREA PROGRAM1, CODE, READONLY
ENTRY
    MOV R0, #NUMBER         ; READ NUMBER FROM MEMORY
    MOVS R1, R0, LSR #1     ; SHIFT LSB TO CARRY
    MOVCS R2, #0xFFFFFFFF   ; IF EVEN
    LDRCC R2, =0x55555555   ; ELSE ODD
    S B S
END
